general:
  log_dir: "logs"
  resolution_tolerance: 0.05
  default_resolution: "1080p"
  default_frame_rate: 30

verify:
  delete_threshold: 90.0
  delete_origin: false
  verify: false
  check_size: true

svt_av1:
  tune: 0
  fast_decode: 1
  preset:
    4k: 3
    2k: 3
    1080p: 3
    720p: 3
    480p: 3
    360p: 3
  crf:
    4k: 30
    2k: 29
    1080p: 28
    720p: 27
    480p: 25
    360p: 24

hevc:
  preset:
    4k: "slow"
    2k: "slow"
    1080p: "slow"
    720p: "slow"
    480p: "slow"
    360p: "slow"
  crf:
    4k: 25
    2k: 24
    1080p: 23
    720p: 22
    480p: 20
    360p: 19

libaom_av1:
  crf:
    4k: 28
    2k: 27
    1080p: 27
    720p: 24
    480p: 21
    360p: 19
  preset:
    4k: 4
    2k: 4
    1080p: 4
    720p: 4
    480p: 4
    360p: 4